//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ChuJiaJiLu {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_ChuJiaJiLu.FRM_ChuJiaJiLu")]
    public interface FRM_ChuJiaJiLu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ChuJiaJiLu/FRM_DiKuaiXiangQing_Load", ReplyAction="http://tempuri.org/FRM_ChuJiaJiLu/FRM_DiKuaiXiangQing_LoadResponse")]
        System.Data.DataSet FRM_DiKuaiXiangQing_Load(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ChuJiaJiLu/FRM_DiKuaiXiangQing_Load", ReplyAction="http://tempuri.org/FRM_ChuJiaJiLu/FRM_DiKuaiXiangQing_LoadResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_DiKuaiXiangQing_LoadAsync(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ChuJiaJiLu/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu", ReplyAction="http://tempuri.org/FRM_ChuJiaJiLu/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLuResponse")]
        System.Data.DataSet FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ChuJiaJiLu/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu", ReplyAction="http://tempuri.org/FRM_ChuJiaJiLu/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLuAsync(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ChuJiaJiLu/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShu", ReplyAction="http://tempuri.org/FRM_ChuJiaJiLu/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShuR" +
            "esponse")]
        System.Data.DataSet FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShu(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ChuJiaJiLu/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShu", ReplyAction="http://tempuri.org/FRM_ChuJiaJiLu/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShuR" +
            "esponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShuAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_ChuJiaJiLuChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ChuJiaJiLu.FRM_ChuJiaJiLu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_ChuJiaJiLuClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ChuJiaJiLu.FRM_ChuJiaJiLu>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ChuJiaJiLu.FRM_ChuJiaJiLu {
        
        public FRM_ChuJiaJiLuClient() {
        }
        
        public FRM_ChuJiaJiLuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_ChuJiaJiLuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_ChuJiaJiLuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_ChuJiaJiLuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_DiKuaiXiangQing_Load(int GuaPaiID) {
            return base.Channel.FRM_DiKuaiXiangQing_Load(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_DiKuaiXiangQing_LoadAsync(int GuaPaiID) {
            return base.Channel.FRM_DiKuaiXiangQing_LoadAsync(GuaPaiID);
        }
        
        public System.Data.DataSet FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLuAsync(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLuAsync(GuaPaiID);
        }
        
        public System.Data.DataSet FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShu(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShu(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShuAsync(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShuAsync(GuaPaiID);
        }
    }
}
