//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_QiTaGongGao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_QiTaGongGao.FRM_QiTaGongGao")]
    public interface FRM_QiTaGongGao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_QiTaGongGao/FRM_QiTaGongGao_Load_QiTaGongGao", ReplyAction="http://tempuri.org/FRM_QiTaGongGao/FRM_QiTaGongGao_Load_QiTaGongGaoResponse")]
        System.Data.DataSet FRM_QiTaGongGao_Load_QiTaGongGao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_QiTaGongGao/FRM_QiTaGongGao_Load_QiTaGongGao", ReplyAction="http://tempuri.org/FRM_QiTaGongGao/FRM_QiTaGongGao_Load_QiTaGongGaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_QiTaGongGao_Load_QiTaGongGaoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_QiTaGongGaoChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_QiTaGongGao.FRM_QiTaGongGao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_QiTaGongGaoClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_QiTaGongGao.FRM_QiTaGongGao>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_QiTaGongGao.FRM_QiTaGongGao {
        
        public FRM_QiTaGongGaoClient() {
        }
        
        public FRM_QiTaGongGaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_QiTaGongGaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_QiTaGongGaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_QiTaGongGaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_QiTaGongGao_Load_QiTaGongGao() {
            return base.Channel.FRM_QiTaGongGao_Load_QiTaGongGao();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_QiTaGongGao_Load_QiTaGongGaoAsync() {
            return base.Channel.FRM_QiTaGongGao_Load_QiTaGongGaoAsync();
        }
    }
}
