//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_DiKuaiXiangQing {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_DiKuaiXiangQing.FRM_DiKuaiXiangQing")]
    public interface FRM_DiKuaiXiangQing {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DiKuaiXiangQing/FRM_DiKuaiXiangQing_Load", ReplyAction="http://tempuri.org/FRM_DiKuaiXiangQing/FRM_DiKuaiXiangQing_LoadResponse")]
        System.Data.DataSet FRM_DiKuaiXiangQing_Load(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DiKuaiXiangQing/FRM_DiKuaiXiangQing_Load", ReplyAction="http://tempuri.org/FRM_DiKuaiXiangQing/FRM_DiKuaiXiangQing_LoadResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_DiKuaiXiangQing_LoadAsync(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DiKuaiXiangQing/FRM_DiKuaiXiangQing_Load1", ReplyAction="http://tempuri.org/FRM_DiKuaiXiangQing/FRM_DiKuaiXiangQing_Load1Response")]
        System.Data.DataSet FRM_DiKuaiXiangQing_Load1(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_DiKuaiXiangQing/FRM_DiKuaiXiangQing_Load1", ReplyAction="http://tempuri.org/FRM_DiKuaiXiangQing/FRM_DiKuaiXiangQing_Load1Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_DiKuaiXiangQing_Load1Async(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_DiKuaiXiangQingChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_DiKuaiXiangQing.FRM_DiKuaiXiangQing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_DiKuaiXiangQingClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_DiKuaiXiangQing.FRM_DiKuaiXiangQing>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_DiKuaiXiangQing.FRM_DiKuaiXiangQing {
        
        public FRM_DiKuaiXiangQingClient() {
        }
        
        public FRM_DiKuaiXiangQingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_DiKuaiXiangQingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_DiKuaiXiangQingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_DiKuaiXiangQingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_DiKuaiXiangQing_Load(int GuaPaiID) {
            return base.Channel.FRM_DiKuaiXiangQing_Load(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_DiKuaiXiangQing_LoadAsync(int GuaPaiID) {
            return base.Channel.FRM_DiKuaiXiangQing_LoadAsync(GuaPaiID);
        }
        
        public System.Data.DataSet FRM_DiKuaiXiangQing_Load1(int GuaPaiID) {
            return base.Channel.FRM_DiKuaiXiangQing_Load1(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_DiKuaiXiangQing_Load1Async(int GuaPaiID) {
            return base.Channel.FRM_DiKuaiXiangQing_Load1Async(GuaPaiID);
        }
    }
}
