//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.Login {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.Login.Login")]
    public interface Login {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login/ChaXunKeHuXinXi_DengLu", ReplyAction="http://tempuri.org/Login/ChaXunKeHuXinXi_DengLuResponse")]
        System.Data.DataSet ChaXunKeHuXinXi_DengLu(string KeHuMingCheng, string ShuZiZhengShuMiMa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login/ChaXunKeHuXinXi_DengLu", ReplyAction="http://tempuri.org/Login/ChaXunKeHuXinXi_DengLuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ChaXunKeHuXinXi_DengLuAsync(string KeHuMingCheng, string ShuZiZhengShuMiMa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.Login.Login, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.Login.Login>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.Login.Login {
        
        public LoginClient() {
        }
        
        public LoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ChaXunKeHuXinXi_DengLu(string KeHuMingCheng, string ShuZiZhengShuMiMa) {
            return base.Channel.ChaXunKeHuXinXi_DengLu(KeHuMingCheng, ShuZiZhengShuMiMa);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ChaXunKeHuXinXi_DengLuAsync(string KeHuMingCheng, string ShuZiZhengShuMiMa) {
            return base.Channel.ChaXunKeHuXinXi_DengLuAsync(KeHuMingCheng, ShuZiZhengShuMiMa);
        }
    }
}
