//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeShouCang {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_WoDeShouCang.FRM_WoDeShouCang")]
    public interface FRM_WoDeShouCang {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeShouCang/FRM_WoDeShouCang_FenYe", ReplyAction="http://tempuri.org/FRM_WoDeShouCang/FRM_WoDeShouCang_FenYeResponse")]
        System.Data.DataSet FRM_WoDeShouCang_FenYe(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeShouCang/FRM_WoDeShouCang_FenYe", ReplyAction="http://tempuri.org/FRM_WoDeShouCang/FRM_WoDeShouCang_FenYeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeShouCang_FenYeAsync(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeShouCang/FRM_WoDeShouCang_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_WoDeShouCang/FRM_WoDeShouCang_FenYeZongShuResponse")]
        System.Data.DataSet FRM_WoDeShouCang_FenYeZongShu(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeShouCang/FRM_WoDeShouCang_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_WoDeShouCang/FRM_WoDeShouCang_FenYeZongShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeShouCang_FenYeZongShuAsync(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeShouCang/btnClickShouCang_YiChuShouCang", ReplyAction="http://tempuri.org/FRM_WoDeShouCang/btnClickShouCang_YiChuShouCangResponse")]
        int btnClickShouCang_YiChuShouCang(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeShouCang/btnClickShouCang_YiChuShouCang", ReplyAction="http://tempuri.org/FRM_WoDeShouCang/btnClickShouCang_YiChuShouCangResponse")]
        System.Threading.Tasks.Task<int> btnClickShouCang_YiChuShouCangAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_WoDeShouCangChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeShouCang.FRM_WoDeShouCang, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_WoDeShouCangClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeShouCang.FRM_WoDeShouCang>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeShouCang.FRM_WoDeShouCang {
        
        public FRM_WoDeShouCangClient() {
        }
        
        public FRM_WoDeShouCangClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_WoDeShouCangClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_WoDeShouCangClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_WoDeShouCangClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_WoDeShouCang_FenYe(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_WoDeShouCang_FenYe(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeShouCang_FenYeAsync(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_WoDeShouCang_FenYeAsync(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Data.DataSet FRM_WoDeShouCang_FenYeZongShu(int KeHuID) {
            return base.Channel.FRM_WoDeShouCang_FenYeZongShu(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeShouCang_FenYeZongShuAsync(int KeHuID) {
            return base.Channel.FRM_WoDeShouCang_FenYeZongShuAsync(KeHuID);
        }
        
        public int btnClickShouCang_YiChuShouCang(int GuaPaiID) {
            return base.Channel.btnClickShouCang_YiChuShouCang(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<int> btnClickShouCang_YiChuShouCangAsync(int GuaPaiID) {
            return base.Channel.btnClickShouCang_YiChuShouCangAsync(GuaPaiID);
        }
    }
}
