//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ZhuFangBaoZhangXingBiLi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_ZhuFangBaoZhangXingBiLi.FRM_ZhuFangBaoZhangXingBiLi")]
    public interface FRM_ZhuFangBaoZhangXingBiLi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "iYuanZhaiYao", ReplyAction="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "iYuanZhaiYaoResponse")]
        System.Data.DataSet FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYao(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "iYuanZhaiYao", ReplyAction="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "iYuanZhaiYaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYaoAsync(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_J" +
            "ingMaiXinXi", ReplyAction="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_J" +
            "ingMaiXinXiResponse")]
        System.Data.DataSet FRM_ZhuFangBaoZhangXingBiLi_Load_JingMaiXinXi(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_J" +
            "ingMaiXinXi", ReplyAction="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_J" +
            "ingMaiXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhuFangBaoZhangXingBiLi_Load_JingMaiXinXiAsync(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "uiJinChuJaiJiLu", ReplyAction="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "uiJinChuJaiJiLuResponse")]
        System.Data.DataSet FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLu(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "uiJinChuJaiJiLu", ReplyAction="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "uiJinChuJaiJiLuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLuAsync(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "uiJinChuJaiJiLu_ZongShu", ReplyAction="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "uiJinChuJaiJiLu_ZongShuResponse")]
        System.Data.DataSet FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLu_ZongShu(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "uiJinChuJaiJiLu_ZongShu", ReplyAction="http://tempuri.org/FRM_ZhuFangBaoZhangXingBiLi/FRM_ZhuFangBaoZhangXingBiLi_Load_Z" +
            "uiJinChuJaiJiLu_ZongShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLu_ZongShuAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_ZhuFangBaoZhangXingBiLiChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ZhuFangBaoZhangXingBiLi.FRM_ZhuFangBaoZhangXingBiLi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_ZhuFangBaoZhangXingBiLiClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ZhuFangBaoZhangXingBiLi.FRM_ZhuFangBaoZhangXingBiLi>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ZhuFangBaoZhangXingBiLi.FRM_ZhuFangBaoZhangXingBiLi {
        
        public FRM_ZhuFangBaoZhangXingBiLiClient() {
        }
        
        public FRM_ZhuFangBaoZhangXingBiLiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_ZhuFangBaoZhangXingBiLiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_ZhuFangBaoZhangXingBiLiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_ZhuFangBaoZhangXingBiLiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYao(int GuaPaiID) {
            return base.Channel.FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYao(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYaoAsync(int GuaPaiID) {
            return base.Channel.FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYaoAsync(GuaPaiID);
        }
        
        public System.Data.DataSet FRM_ZhuFangBaoZhangXingBiLi_Load_JingMaiXinXi(int GuaPaiID) {
            return base.Channel.FRM_ZhuFangBaoZhangXingBiLi_Load_JingMaiXinXi(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhuFangBaoZhangXingBiLi_Load_JingMaiXinXiAsync(int GuaPaiID) {
            return base.Channel.FRM_ZhuFangBaoZhangXingBiLi_Load_JingMaiXinXiAsync(GuaPaiID);
        }
        
        public System.Data.DataSet FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLu(int GuaPaiID) {
            return base.Channel.FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLu(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLuAsync(int GuaPaiID) {
            return base.Channel.FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLuAsync(GuaPaiID);
        }
        
        public System.Data.DataSet FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLu_ZongShu(int GuaPaiID) {
            return base.Channel.FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLu_ZongShu(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLu_ZongShuAsync(int GuaPaiID) {
            return base.Channel.FRM_ZhuFangBaoZhangXingBiLi_Load_ZuiJinChuJaiJiLu_ZongShuAsync(GuaPaiID);
        }
    }
}
