//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_XunZeYinHang {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_XunZeYinHang.FRM_XunZeYinHang")]
    public interface FRM_XunZeYinHang {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XunZeYinHang/FRM_XunZeYinHang_Load", ReplyAction="http://tempuri.org/FRM_XunZeYinHang/FRM_XunZeYinHang_LoadResponse")]
        System.Data.DataSet FRM_XunZeYinHang_Load(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_XunZeYinHang/FRM_XunZeYinHang_Load", ReplyAction="http://tempuri.org/FRM_XunZeYinHang/FRM_XunZeYinHang_LoadResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_XunZeYinHang_LoadAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_XunZeYinHangChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_XunZeYinHang.FRM_XunZeYinHang, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_XunZeYinHangClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_XunZeYinHang.FRM_XunZeYinHang>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_XunZeYinHang.FRM_XunZeYinHang {
        
        public FRM_XunZeYinHangClient() {
        }
        
        public FRM_XunZeYinHangClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_XunZeYinHangClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XunZeYinHangClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_XunZeYinHangClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_XunZeYinHang_Load(int GuaPaiID) {
            return base.Channel.FRM_XunZeYinHang_Load(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_XunZeYinHang_LoadAsync(int GuaPaiID) {
            return base.Channel.FRM_XunZeYinHang_LoadAsync(GuaPaiID);
        }
    }
}
