//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ZhiFuGuanLi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_ZhiFuGuanLi.FRM_ZhiFuGuanLi")]
    public interface FRM_ZhiFuGuanLi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/FRM_ZhiFuGuanLi_Load_XingZhengQuMingCheng", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/FRM_ZhiFuGuanLi_Load_XingZhengQuMingChengRespo" +
            "nse")]
        System.Data.DataSet FRM_ZhiFuGuanLi_Load_XingZhengQuMingCheng();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/FRM_ZhiFuGuanLi_Load_XingZhengQuMingCheng", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/FRM_ZhiFuGuanLi_Load_XingZhengQuMingChengRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhiFuGuanLi_Load_XingZhengQuMingChengAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaZhao_Click_DongTaiTiaoJianChaZhao", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaZhao_Click_DongTaiTiaoJianChaZhaoRespons" +
            "e")]
        System.Data.DataSet btnChaZhao_Click_DongTaiTiaoJianChaZhao(string DongTaiTiaoJian);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaZhao_Click_DongTaiTiaoJianChaZhao", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaZhao_Click_DongTaiTiaoJianChaZhaoRespons" +
            "e")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnChaZhao_Click_DongTaiTiaoJianChaZhaoAsync(string DongTaiTiaoJian);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_FenYe", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeRespo" +
            "nse")]
        System.Data.DataSet btnChaKanQuanBu_Click_QuanBuChaZhao_FenYe(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_FenYe", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeAsync(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeZongS" +
            "hu", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeZongS" +
            "huResponse")]
        System.Data.DataSet btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeZongShu(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeZongS" +
            "hu", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeZongS" +
            "huResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeZongShuAsync(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaZhao1_Click_TiaoJianChaZhao", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaZhao1_Click_TiaoJianChaZhaoResponse")]
        System.Data.DataSet btnChaZhao1_Click_TiaoJianChaZhao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaZhao1_Click_TiaoJianChaZhao", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaZhao1_Click_TiaoJianChaZhaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnChaZhao1_Click_TiaoJianChaZhaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu1_Click_ChaZhaoQuanBu", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu1_Click_ChaZhaoQuanBuResponse")]
        System.Data.DataSet btnChaKanQuanBu1_Click_ChaZhaoQuanBu(int YeMa, int MeiYeShuLiang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu1_Click_ChaZhaoQuanBu", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu1_Click_ChaZhaoQuanBuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnChaKanQuanBu1_Click_ChaZhaoQuanBuAsync(int YeMa, int MeiYeShuLiang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_ZongShu", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_ZongShuRes" +
            "ponse")]
        System.Data.DataSet btnChaKanQuanBu_Click_QuanBuChaZhao_ZongShu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_ZongShu", ReplyAction="http://tempuri.org/FRM_ZhiFuGuanLi/btnChaKanQuanBu_Click_QuanBuChaZhao_ZongShuRes" +
            "ponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnChaKanQuanBu_Click_QuanBuChaZhao_ZongShuAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_ZhiFuGuanLiChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ZhiFuGuanLi.FRM_ZhiFuGuanLi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_ZhiFuGuanLiClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ZhiFuGuanLi.FRM_ZhiFuGuanLi>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ZhiFuGuanLi.FRM_ZhiFuGuanLi {
        
        public FRM_ZhiFuGuanLiClient() {
        }
        
        public FRM_ZhiFuGuanLiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_ZhiFuGuanLiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_ZhiFuGuanLiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_ZhiFuGuanLiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_ZhiFuGuanLi_Load_XingZhengQuMingCheng() {
            return base.Channel.FRM_ZhiFuGuanLi_Load_XingZhengQuMingCheng();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhiFuGuanLi_Load_XingZhengQuMingChengAsync() {
            return base.Channel.FRM_ZhiFuGuanLi_Load_XingZhengQuMingChengAsync();
        }
        
        public System.Data.DataSet btnChaZhao_Click_DongTaiTiaoJianChaZhao(string DongTaiTiaoJian) {
            return base.Channel.btnChaZhao_Click_DongTaiTiaoJianChaZhao(DongTaiTiaoJian);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnChaZhao_Click_DongTaiTiaoJianChaZhaoAsync(string DongTaiTiaoJian) {
            return base.Channel.btnChaZhao_Click_DongTaiTiaoJianChaZhaoAsync(DongTaiTiaoJian);
        }
        
        public System.Data.DataSet btnChaKanQuanBu_Click_QuanBuChaZhao_FenYe(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.btnChaKanQuanBu_Click_QuanBuChaZhao_FenYe(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeAsync(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeAsync(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Data.DataSet btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeZongShu(int KeHuID) {
            return base.Channel.btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeZongShu(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeZongShuAsync(int KeHuID) {
            return base.Channel.btnChaKanQuanBu_Click_QuanBuChaZhao_FenYeZongShuAsync(KeHuID);
        }
        
        public System.Data.DataSet btnChaZhao1_Click_TiaoJianChaZhao() {
            return base.Channel.btnChaZhao1_Click_TiaoJianChaZhao();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnChaZhao1_Click_TiaoJianChaZhaoAsync() {
            return base.Channel.btnChaZhao1_Click_TiaoJianChaZhaoAsync();
        }
        
        public System.Data.DataSet btnChaKanQuanBu1_Click_ChaZhaoQuanBu(int YeMa, int MeiYeShuLiang) {
            return base.Channel.btnChaKanQuanBu1_Click_ChaZhaoQuanBu(YeMa, MeiYeShuLiang);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnChaKanQuanBu1_Click_ChaZhaoQuanBuAsync(int YeMa, int MeiYeShuLiang) {
            return base.Channel.btnChaKanQuanBu1_Click_ChaZhaoQuanBuAsync(YeMa, MeiYeShuLiang);
        }
        
        public System.Data.DataSet btnChaKanQuanBu_Click_QuanBuChaZhao_ZongShu() {
            return base.Channel.btnChaKanQuanBu_Click_QuanBuChaZhao_ZongShu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnChaKanQuanBu_Click_QuanBuChaZhao_ZongShuAsync() {
            return base.Channel.btnChaKanQuanBu_Click_QuanBuChaZhao_ZongShuAsync();
        }
    }
}
