//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_PaiMaiDaTing {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_PaiMaiDaTing.FRM_PaiMaiDaTing")]
    public interface FRM_PaiMaiDaTing {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZiYuanZhaiYao", ReplyAction="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZiYuanZhaiYaoResponse")]
        System.Data.DataSet FRM_PaiMaiDaTing_Load_ZiYuanZhaiYao(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZiYuanZhaiYao", ReplyAction="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZiYuanZhaiYaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ZiYuanZhaiYaoAsync(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_JingMaiXinXi", ReplyAction="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_JingMaiXinXiResponse")]
        System.Data.DataSet FRM_PaiMaiDaTing_Load_JingMaiXinXi(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_JingMaiXinXi", ReplyAction="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_JingMaiXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_JingMaiXinXiAsync(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ChuJiaFuDu", ReplyAction="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ChuJiaFuDuResponse")]
        System.Data.DataSet FRM_PaiMaiDaTing_Load_ChuJiaFuDu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ChuJiaFuDu", ReplyAction="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ChuJiaFuDuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ChuJiaFuDuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu", ReplyAction="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLuRespons" +
            "e")]
        System.Data.DataSet FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu", ReplyAction="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLuRespons" +
            "e")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLuAsync(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongSh" +
            "u", ReplyAction="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongSh" +
            "uResponse")]
        System.Data.DataSet FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShu(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongSh" +
            "u", ReplyAction="http://tempuri.org/FRM_PaiMaiDaTing/FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongSh" +
            "uResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShuAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_PaiMaiDaTingChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_PaiMaiDaTing.FRM_PaiMaiDaTing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_PaiMaiDaTingClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_PaiMaiDaTing.FRM_PaiMaiDaTing>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_PaiMaiDaTing.FRM_PaiMaiDaTing {
        
        public FRM_PaiMaiDaTingClient() {
        }
        
        public FRM_PaiMaiDaTingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_PaiMaiDaTingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PaiMaiDaTingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_PaiMaiDaTingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_PaiMaiDaTing_Load_ZiYuanZhaiYao(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_ZiYuanZhaiYao(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ZiYuanZhaiYaoAsync(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_ZiYuanZhaiYaoAsync(GuaPaiID);
        }
        
        public System.Data.DataSet FRM_PaiMaiDaTing_Load_JingMaiXinXi(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_JingMaiXinXi(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_JingMaiXinXiAsync(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_JingMaiXinXiAsync(GuaPaiID);
        }
        
        public System.Data.DataSet FRM_PaiMaiDaTing_Load_ChuJiaFuDu() {
            return base.Channel.FRM_PaiMaiDaTing_Load_ChuJiaFuDu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ChuJiaFuDuAsync() {
            return base.Channel.FRM_PaiMaiDaTing_Load_ChuJiaFuDuAsync();
        }
        
        public System.Data.DataSet FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLuAsync(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLuAsync(GuaPaiID);
        }
        
        public System.Data.DataSet FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShu(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShu(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShuAsync(int GuaPaiID) {
            return base.Channel.FRM_PaiMaiDaTing_Load_ZuiJinChuJaiJiLu_ZongShuAsync(GuaPaiID);
        }
    }
}
