//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeWenDang {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_WoDeWenDang.FRM_WoDeWenDang")]
    public interface FRM_WoDeWenDang {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeWenDang/btnChaZhao_Click_DongTaiTiaoJian", ReplyAction="http://tempuri.org/FRM_WoDeWenDang/btnChaZhao_Click_DongTaiTiaoJianResponse")]
        System.Data.DataSet btnChaZhao_Click_DongTaiTiaoJian(string DongTaiTiaoJian);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeWenDang/btnChaZhao_Click_DongTaiTiaoJian", ReplyAction="http://tempuri.org/FRM_WoDeWenDang/btnChaZhao_Click_DongTaiTiaoJianResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnChaZhao_Click_DongTaiTiaoJianAsync(string DongTaiTiaoJian);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeWenDang/btnChaZhao_Click_DongTaiTiaoJian_ZongShu", ReplyAction="http://tempuri.org/FRM_WoDeWenDang/btnChaZhao_Click_DongTaiTiaoJian_ZongShuRespon" +
            "se")]
        System.Data.DataSet btnChaZhao_Click_DongTaiTiaoJian_ZongShu(string DongTaiTiaoJian);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeWenDang/btnChaZhao_Click_DongTaiTiaoJian_ZongShu", ReplyAction="http://tempuri.org/FRM_WoDeWenDang/btnChaZhao_Click_DongTaiTiaoJian_ZongShuRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnChaZhao_Click_DongTaiTiaoJian_ZongShuAsync(string DongTaiTiaoJian);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeWenDang/btnChaKanQuanBu_Click_WoDeWenDang", ReplyAction="http://tempuri.org/FRM_WoDeWenDang/btnChaKanQuanBu_Click_WoDeWenDangResponse")]
        System.Data.DataSet btnChaKanQuanBu_Click_WoDeWenDang(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeWenDang/btnChaKanQuanBu_Click_WoDeWenDang", ReplyAction="http://tempuri.org/FRM_WoDeWenDang/btnChaKanQuanBu_Click_WoDeWenDangResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnChaKanQuanBu_Click_WoDeWenDangAsync(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeWenDang/FRM_HuoQuBaoZhangJinZhangHao_Load", ReplyAction="http://tempuri.org/FRM_WoDeWenDang/FRM_HuoQuBaoZhangJinZhangHao_LoadResponse")]
        System.Data.DataSet FRM_HuoQuBaoZhangJinZhangHao_Load(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeWenDang/FRM_HuoQuBaoZhangJinZhangHao_Load", ReplyAction="http://tempuri.org/FRM_WoDeWenDang/FRM_HuoQuBaoZhangJinZhangHao_LoadResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_HuoQuBaoZhangJinZhangHao_LoadAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_WoDeWenDangChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeWenDang.FRM_WoDeWenDang, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_WoDeWenDangClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeWenDang.FRM_WoDeWenDang>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeWenDang.FRM_WoDeWenDang {
        
        public FRM_WoDeWenDangClient() {
        }
        
        public FRM_WoDeWenDangClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_WoDeWenDangClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_WoDeWenDangClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_WoDeWenDangClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet btnChaZhao_Click_DongTaiTiaoJian(string DongTaiTiaoJian) {
            return base.Channel.btnChaZhao_Click_DongTaiTiaoJian(DongTaiTiaoJian);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnChaZhao_Click_DongTaiTiaoJianAsync(string DongTaiTiaoJian) {
            return base.Channel.btnChaZhao_Click_DongTaiTiaoJianAsync(DongTaiTiaoJian);
        }
        
        public System.Data.DataSet btnChaZhao_Click_DongTaiTiaoJian_ZongShu(string DongTaiTiaoJian) {
            return base.Channel.btnChaZhao_Click_DongTaiTiaoJian_ZongShu(DongTaiTiaoJian);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnChaZhao_Click_DongTaiTiaoJian_ZongShuAsync(string DongTaiTiaoJian) {
            return base.Channel.btnChaZhao_Click_DongTaiTiaoJian_ZongShuAsync(DongTaiTiaoJian);
        }
        
        public System.Data.DataSet btnChaKanQuanBu_Click_WoDeWenDang(int KeHuID) {
            return base.Channel.btnChaKanQuanBu_Click_WoDeWenDang(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnChaKanQuanBu_Click_WoDeWenDangAsync(int KeHuID) {
            return base.Channel.btnChaKanQuanBu_Click_WoDeWenDangAsync(KeHuID);
        }
        
        public System.Data.DataSet FRM_HuoQuBaoZhangJinZhangHao_Load(int GuaPaiID) {
            return base.Channel.FRM_HuoQuBaoZhangJinZhangHao_Load(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_HuoQuBaoZhangJinZhangHao_LoadAsync(int GuaPaiID) {
            return base.Channel.FRM_HuoQuBaoZhangJinZhangHao_LoadAsync(GuaPaiID);
        }
    }
}
