//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeJiaoYi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_WoDeJiaoYi.FRM_WoDeJiaoYi")]
    public interface FRM_WoDeJiaoYi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYe", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeResponse")]
        System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYe(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYe", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeAsync(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShuResponse")]
        System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYeZongShu(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeZongShuAsync(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZhengZaiGuaPai", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZhengZaiGuaPaiResponse" +
            "")]
        System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYeZhengZaiGuaPai(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZhengZaiGuaPai", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZhengZaiGuaPaiResponse" +
            "")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeZhengZaiGuaPaiAsync(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShuZhengZaiGuaPai", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShuZhengZaiGuaPaiR" +
            "esponse")]
        System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYeZongShuZhengZaiGuaPai(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShuZhengZaiGuaPai", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShuZhengZaiGuaPaiR" +
            "esponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeZongShuZhengZaiGuaPaiAsync(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeGuaPaiGongShi", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeGuaPaiGongShiResponse")]
        System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYeGuaPaiGongShi(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeGuaPaiGongShi", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeGuaPaiGongShiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeGuaPaiGongShiAsync(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShuGuaPaiGongShi", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShuGuaPaiGongShiRe" +
            "sponse")]
        System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYeZongShuGuaPaiGongShi(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShuGuaPaiGongShi", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_FenYeZongShuGuaPaiGongShiRe" +
            "sponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeZongShuGuaPaiGongShiAsync(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_XingZhengQu", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_XingZhengQuResponse")]
        System.Data.DataSet FRM_WoDeJiaoYi_Load_XingZhengQu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_XingZhengQu", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/FRM_WoDeJiaoYi_Load_XingZhengQuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_XingZhengQuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJianRespo" +
            "nse")]
        System.Data.DataSet btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian(string GuaPaiBianHao, System.DateTime GuaPaiQiShiShiJian, System.DateTime GuaPaiJieZhiShiJian, string TuDiWeiZhi, string KeHuMingCheng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJianRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJianAsync(string GuaPaiBianHao, System.DateTime GuaPaiQiShiShiJian, System.DateTime GuaPaiJieZhiShiJian, string TuDiWeiZhi, string KeHuMingCheng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian_Zong" +
            "Shu", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian_Zong" +
            "ShuResponse")]
        System.Data.DataSet btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian_ZongShu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian_Zong" +
            "Shu", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian_Zong" +
            "ShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian_ZongShuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/btnClickChuJai_ShiFouYouBaoZhangXingZhuFang", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/btnClickChuJai_ShiFouYouBaoZhangXingZhuFangResp" +
            "onse")]
        System.Data.DataSet btnClickChuJai_ShiFouYouBaoZhangXingZhuFang(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_WoDeJiaoYi/btnClickChuJai_ShiFouYouBaoZhangXingZhuFang", ReplyAction="http://tempuri.org/FRM_WoDeJiaoYi/btnClickChuJai_ShiFouYouBaoZhangXingZhuFangResp" +
            "onse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnClickChuJai_ShiFouYouBaoZhangXingZhuFangAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_WoDeJiaoYiChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeJiaoYi.FRM_WoDeJiaoYi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_WoDeJiaoYiClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeJiaoYi.FRM_WoDeJiaoYi>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_WoDeJiaoYi.FRM_WoDeJiaoYi {
        
        public FRM_WoDeJiaoYiClient() {
        }
        
        public FRM_WoDeJiaoYiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_WoDeJiaoYiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_WoDeJiaoYiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_WoDeJiaoYiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYe(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYe(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeAsync(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeAsync(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYeZongShu(int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeZongShu(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeZongShuAsync(int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeZongShuAsync(KeHuID);
        }
        
        public System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYeZhengZaiGuaPai(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeZhengZaiGuaPai(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeZhengZaiGuaPaiAsync(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeZhengZaiGuaPaiAsync(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYeZongShuZhengZaiGuaPai(int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeZongShuZhengZaiGuaPai(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeZongShuZhengZaiGuaPaiAsync(int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeZongShuZhengZaiGuaPaiAsync(KeHuID);
        }
        
        public System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYeGuaPaiGongShi(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeGuaPaiGongShi(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeGuaPaiGongShiAsync(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeGuaPaiGongShiAsync(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Data.DataSet FRM_WoDeJiaoYi_Load_FenYeZongShuGuaPaiGongShi(int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeZongShuGuaPaiGongShi(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_FenYeZongShuGuaPaiGongShiAsync(int KeHuID) {
            return base.Channel.FRM_WoDeJiaoYi_Load_FenYeZongShuGuaPaiGongShiAsync(KeHuID);
        }
        
        public System.Data.DataSet FRM_WoDeJiaoYi_Load_XingZhengQu() {
            return base.Channel.FRM_WoDeJiaoYi_Load_XingZhengQu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_WoDeJiaoYi_Load_XingZhengQuAsync() {
            return base.Channel.FRM_WoDeJiaoYi_Load_XingZhengQuAsync();
        }
        
        public System.Data.DataSet btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian(string GuaPaiBianHao, System.DateTime GuaPaiQiShiShiJian, System.DateTime GuaPaiJieZhiShiJian, string TuDiWeiZhi, string KeHuMingCheng) {
            return base.Channel.btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian(GuaPaiBianHao, GuaPaiQiShiShiJian, GuaPaiJieZhiShiJian, TuDiWeiZhi, KeHuMingCheng);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJianAsync(string GuaPaiBianHao, System.DateTime GuaPaiQiShiShiJian, System.DateTime GuaPaiJieZhiShiJian, string TuDiWeiZhi, string KeHuMingCheng) {
            return base.Channel.btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJianAsync(GuaPaiBianHao, GuaPaiQiShiShiJian, GuaPaiJieZhiShiJian, TuDiWeiZhi, KeHuMingCheng);
        }
        
        public System.Data.DataSet btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian_ZongShu() {
            return base.Channel.btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian_ZongShu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian_ZongShuAsync() {
            return base.Channel.btnSouSuo_Click_WoDeJiaoYi_DongTaiTiaoJian_ZongShuAsync();
        }
        
        public System.Data.DataSet btnClickChuJai_ShiFouYouBaoZhangXingZhuFang(int GuaPaiID) {
            return base.Channel.btnClickChuJai_ShiFouYouBaoZhangXingZhuFang(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnClickChuJai_ShiFouYouBaoZhangXingZhuFangAsync(int GuaPaiID) {
            return base.Channel.btnClickChuJai_ShiFouYouBaoZhangXingZhuFangAsync(GuaPaiID);
        }
    }
}
