//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JIaoYiDaTingZhuYe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_JIaoYiDaTingZhuYe.FRM_JIaoYiDaTingZhuYe")]
    public interface FRM_JIaoYiDaTingZhuYe {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_FenYe", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_FenYeResponse" +
            "")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Load_FenYe(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_FenYe", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_FenYeResponse" +
            "")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Load_FenYeAsync(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_FenYeZongShuR" +
            "esponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Load_FenYeZongShu(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_FenYeZongShuR" +
            "esponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Load_FenYeZongShuAsync(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_XingZhengQu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_XingZhengQuRe" +
            "sponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Load_XingZhengQu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_XingZhengQu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Load_XingZhengQuRe" +
            "sponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Load_XingZhengQuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongG" +
            "ao", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongG" +
            "aoResponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGao(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongG" +
            "ao", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongG" +
            "aoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGaoAsync(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongG" +
            "ao_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongG" +
            "ao_FenYeZongShuResponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGao_FenYeZongShu(int JiaoYiZhuangTaiID, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongG" +
            "ao_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongG" +
            "ao_FenYeZongShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGao_FenYeZongShuAsync(int JiaoYiZhuangTaiID, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGua" +
            "Pai", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGua" +
            "PaiResponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPai(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGua" +
            "Pai", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGua" +
            "PaiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPaiAsync(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGua" +
            "Pai_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGua" +
            "Pai_FenYeZongShuResponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPai_FenYeZongShu(int JiaoYiZhuangTaiID, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGua" +
            "Pai_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGua" +
            "Pai_FenYeZongShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPai_FenYeZongShuAsync(int JiaoYiZhuangTaiID, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongS" +
            "hi", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongS" +
            "hiResponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShi(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongS" +
            "hi", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongS" +
            "hiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShiAsync(int YeMa, int MeiYeShuLiang, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongS" +
            "hi_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongS" +
            "hi_FenYeZongShuResponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShi_FenYeZongShu(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongS" +
            "hi_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongS" +
            "hi_FenYeZongShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShi_FenYeZongShuAsync(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_YuGongGao", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_YuGongGaoRe" +
            "sponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_YuGongGao(int YeMa, int MeiYeShuLiang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_YuGongGao", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_YuGongGaoRe" +
            "sponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_YuGongGaoAsync(int YeMa, int MeiYeShuLiang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_YuGongGao_F" +
            "enYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_YuGongGao_F" +
            "enYeZongShuResponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_YuGongGao_FenYeZongShu(int GongGaoLeiXingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_YuGongGao_F" +
            "enYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_YuGongGao_F" +
            "enYeZongShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_YuGongGao_FenYeZongShuAsync(int GongGaoLeiXingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao" +
            "", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao" +
            "Response")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao(int YeMa, int MeiYeShuLiang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao" +
            "", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao" +
            "Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGaoAsync(int YeMa, int MeiYeShuLiang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao" +
            "_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao" +
            "_FenYeZongShuResponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao_FenYeZongShu(int GongGaoLeiXingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao" +
            "_FenYeZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao" +
            "_FenYeZongShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao_FenYeZongShuAsync(int GongGaoLeiXingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnSouSuo_Click_SelectDongTaiTiaoJian", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnSouSuo_Click_SelectDongTaiTiaoJianRes" +
            "ponse")]
        System.Data.DataSet btnSouSuo_Click_SelectDongTaiTiaoJian(string GuaPaiBianHao, System.DateTime GuaPaiQiShiShiJian, System.DateTime GuaPaiJieZhiShiJian, string TuDiWeiZhi, string KeHuMingCheng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnSouSuo_Click_SelectDongTaiTiaoJian", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnSouSuo_Click_SelectDongTaiTiaoJianRes" +
            "ponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnSouSuo_Click_SelectDongTaiTiaoJianAsync(string GuaPaiBianHao, System.DateTime GuaPaiQiShiShiJian, System.DateTime GuaPaiJieZhiShiJian, string TuDiWeiZhi, string KeHuMingCheng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnSouSuo_Click_SelectDongTaiTiaoJian_Zo" +
            "ngShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnSouSuo_Click_SelectDongTaiTiaoJian_Zo" +
            "ngShuResponse")]
        System.Data.DataSet btnSouSuo_Click_SelectDongTaiTiaoJian_ZongShu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnSouSuo_Click_SelectDongTaiTiaoJian_Zo" +
            "ngShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnSouSuo_Click_SelectDongTaiTiaoJian_Zo" +
            "ngShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnSouSuo_Click_SelectDongTaiTiaoJian_ZongShuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiCha" +
            "Xun", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiCha" +
            "XunResponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXun(int YeMa, int MeiYeShuLiang, int JiaoYiLeiBieID, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiCha" +
            "Xun", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiCha" +
            "XunResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXunAsync(int YeMa, int MeiYeShuLiang, int JiaoYiLeiBieID, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiCha" +
            "XunZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiCha" +
            "XunZongShuResponse")]
        System.Data.DataSet FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXunZongShu(int JiaoYiLeiBieID, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiCha" +
            "XunZongShu", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiCha" +
            "XunZongShuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXunZongShuAsync(int JiaoYiLeiBieID, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnClickShouCang_ShiFouShouCang", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnClickShouCang_ShiFouShouCangResponse")]
        System.Data.DataSet btnClickShouCang_ShiFouShouCang(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnClickShouCang_ShiFouShouCang", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/btnClickShouCang_ShiFouShouCangResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnClickShouCang_ShiFouShouCangAsync(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_InsertShouCangBiao" +
            "", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_InsertShouCangBiao" +
            "Response")]
        int FRM_JIaoYiDaTingZhuYe_InsertShouCangBiao(int GuaPaiID, int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_InsertShouCangBiao" +
            "", ReplyAction="http://tempuri.org/FRM_JIaoYiDaTingZhuYe/FRM_JIaoYiDaTingZhuYe_InsertShouCangBiao" +
            "Response")]
        System.Threading.Tasks.Task<int> FRM_JIaoYiDaTingZhuYe_InsertShouCangBiaoAsync(int GuaPaiID, int KeHuID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_JIaoYiDaTingZhuYeChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JIaoYiDaTingZhuYe.FRM_JIaoYiDaTingZhuYe, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_JIaoYiDaTingZhuYeClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JIaoYiDaTingZhuYe.FRM_JIaoYiDaTingZhuYe>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JIaoYiDaTingZhuYe.FRM_JIaoYiDaTingZhuYe {
        
        public FRM_JIaoYiDaTingZhuYeClient() {
        }
        
        public FRM_JIaoYiDaTingZhuYeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_JIaoYiDaTingZhuYeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JIaoYiDaTingZhuYeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JIaoYiDaTingZhuYeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Load_FenYe(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Load_FenYe(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Load_FenYeAsync(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Load_FenYeAsync(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Load_FenYeZongShu(int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Load_FenYeZongShu(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Load_FenYeZongShuAsync(int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Load_FenYeZongShuAsync(KeHuID);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Load_XingZhengQu() {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Load_XingZhengQu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Load_XingZhengQuAsync() {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Load_XingZhengQuAsync();
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGao(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGao(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGaoAsync(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGaoAsync(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGao_FenYeZongShu(int JiaoYiZhuangTaiID, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGao_FenYeZongShu(JiaoYiZhuangTaiID, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGao_FenYeZongShuAsync(int JiaoYiZhuangTaiID, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_GuaPaiGongGao_FenYeZongShuAsync(JiaoYiZhuangTaiID, KeHuID);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPai(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPai(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPaiAsync(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPaiAsync(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPai_FenYeZongShu(int JiaoYiZhuangTaiID, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPai_FenYeZongShu(JiaoYiZhuangTaiID, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPai_FenYeZongShuAsync(int JiaoYiZhuangTaiID, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_ZhengZaiGuaPai_FenYeZongShuAsync(JiaoYiZhuangTaiID, KeHuID);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShi(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShi(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShiAsync(int YeMa, int MeiYeShuLiang, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShiAsync(YeMa, MeiYeShuLiang, KeHuID);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShi_FenYeZongShu(int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShi_FenYeZongShu(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShi_FenYeZongShuAsync(int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_JieGuoGongShi_FenYeZongShuAsync(KeHuID);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_YuGongGao(int YeMa, int MeiYeShuLiang) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_YuGongGao(YeMa, MeiYeShuLiang);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_YuGongGaoAsync(int YeMa, int MeiYeShuLiang) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_YuGongGaoAsync(YeMa, MeiYeShuLiang);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_YuGongGao_FenYeZongShu(int GongGaoLeiXingID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_YuGongGao_FenYeZongShu(GongGaoLeiXingID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_YuGongGao_FenYeZongShuAsync(int GongGaoLeiXingID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_YuGongGao_FenYeZongShuAsync(GongGaoLeiXingID);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao(int YeMa, int MeiYeShuLiang) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao(YeMa, MeiYeShuLiang);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGaoAsync(int YeMa, int MeiYeShuLiang) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGaoAsync(YeMa, MeiYeShuLiang);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao_FenYeZongShu(int GongGaoLeiXingID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao_FenYeZongShu(GongGaoLeiXingID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao_FenYeZongShuAsync(int GongGaoLeiXingID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_Select_QiTaGongGao_FenYeZongShuAsync(GongGaoLeiXingID);
        }
        
        public System.Data.DataSet btnSouSuo_Click_SelectDongTaiTiaoJian(string GuaPaiBianHao, System.DateTime GuaPaiQiShiShiJian, System.DateTime GuaPaiJieZhiShiJian, string TuDiWeiZhi, string KeHuMingCheng) {
            return base.Channel.btnSouSuo_Click_SelectDongTaiTiaoJian(GuaPaiBianHao, GuaPaiQiShiShiJian, GuaPaiJieZhiShiJian, TuDiWeiZhi, KeHuMingCheng);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnSouSuo_Click_SelectDongTaiTiaoJianAsync(string GuaPaiBianHao, System.DateTime GuaPaiQiShiShiJian, System.DateTime GuaPaiJieZhiShiJian, string TuDiWeiZhi, string KeHuMingCheng) {
            return base.Channel.btnSouSuo_Click_SelectDongTaiTiaoJianAsync(GuaPaiBianHao, GuaPaiQiShiShiJian, GuaPaiJieZhiShiJian, TuDiWeiZhi, KeHuMingCheng);
        }
        
        public System.Data.DataSet btnSouSuo_Click_SelectDongTaiTiaoJian_ZongShu() {
            return base.Channel.btnSouSuo_Click_SelectDongTaiTiaoJian_ZongShu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnSouSuo_Click_SelectDongTaiTiaoJian_ZongShuAsync() {
            return base.Channel.btnSouSuo_Click_SelectDongTaiTiaoJian_ZongShuAsync();
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXun(int YeMa, int MeiYeShuLiang, int JiaoYiLeiBieID, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXun(YeMa, MeiYeShuLiang, JiaoYiLeiBieID, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXunAsync(int YeMa, int MeiYeShuLiang, int JiaoYiLeiBieID, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXunAsync(YeMa, MeiYeShuLiang, JiaoYiLeiBieID, KeHuID);
        }
        
        public System.Data.DataSet FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXunZongShu(int JiaoYiLeiBieID, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXunZongShu(JiaoYiLeiBieID, KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXunZongShuAsync(int JiaoYiLeiBieID, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_JiaoYiZhuangTaiChaXunZongShuAsync(JiaoYiLeiBieID, KeHuID);
        }
        
        public System.Data.DataSet btnClickShouCang_ShiFouShouCang(int KeHuID) {
            return base.Channel.btnClickShouCang_ShiFouShouCang(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnClickShouCang_ShiFouShouCangAsync(int KeHuID) {
            return base.Channel.btnClickShouCang_ShiFouShouCangAsync(KeHuID);
        }
        
        public int FRM_JIaoYiDaTingZhuYe_InsertShouCangBiao(int GuaPaiID, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_InsertShouCangBiao(GuaPaiID, KeHuID);
        }
        
        public System.Threading.Tasks.Task<int> FRM_JIaoYiDaTingZhuYe_InsertShouCangBiaoAsync(int GuaPaiID, int KeHuID) {
            return base.Channel.FRM_JIaoYiDaTingZhuYe_InsertShouCangBiaoAsync(GuaPaiID, KeHuID);
        }
    }
}
