//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JingMaiShenQingShu {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_JingMaiShenQingShu.FRM_JingMaiShenQingShu")]
    public interface FRM_JingMaiShenQingShu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JingMaiShenQingShu/FRM_HuoQuBaoZhangJinZhangHao_Load", ReplyAction="http://tempuri.org/FRM_JingMaiShenQingShu/FRM_HuoQuBaoZhangJinZhangHao_LoadRespon" +
            "se")]
        System.Data.DataSet FRM_HuoQuBaoZhangJinZhangHao_Load(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JingMaiShenQingShu/FRM_HuoQuBaoZhangJinZhangHao_Load", ReplyAction="http://tempuri.org/FRM_JingMaiShenQingShu/FRM_HuoQuBaoZhangJinZhangHao_LoadRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_HuoQuBaoZhangJinZhangHao_LoadAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_JingMaiShenQingShuChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JingMaiShenQingShu.FRM_JingMaiShenQingShu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_JingMaiShenQingShuClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JingMaiShenQingShu.FRM_JingMaiShenQingShu>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JingMaiShenQingShu.FRM_JingMaiShenQingShu {
        
        public FRM_JingMaiShenQingShuClient() {
        }
        
        public FRM_JingMaiShenQingShuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_JingMaiShenQingShuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JingMaiShenQingShuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JingMaiShenQingShuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_HuoQuBaoZhangJinZhangHao_Load(int GuaPaiID) {
            return base.Channel.FRM_HuoQuBaoZhangJinZhangHao_Load(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_HuoQuBaoZhangJinZhangHao_LoadAsync(int GuaPaiID) {
            return base.Channel.FRM_HuoQuBaoZhangJinZhangHao_LoadAsync(GuaPaiID);
        }
    }
}
