//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_GeRenZiLiao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_GeRenZiLiao.FRM_GeRenZiLiao")]
    public interface FRM_GeRenZiLiao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_GeRenZiLiao/FRM_GeRenZiLiao_Load_GeRenXinXi", ReplyAction="http://tempuri.org/FRM_GeRenZiLiao/FRM_GeRenZiLiao_Load_GeRenXinXiResponse")]
        System.Data.DataSet FRM_GeRenZiLiao_Load_GeRenXinXi(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_GeRenZiLiao/FRM_GeRenZiLiao_Load_GeRenXinXi", ReplyAction="http://tempuri.org/FRM_GeRenZiLiao/FRM_GeRenZiLiao_Load_GeRenXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_GeRenZiLiao_Load_GeRenXinXiAsync(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_GeRenZiLiao/FRM_GeRenZiLiao_Load_QiYeXinXi", ReplyAction="http://tempuri.org/FRM_GeRenZiLiao/FRM_GeRenZiLiao_Load_QiYeXinXiResponse")]
        System.Data.DataSet FRM_GeRenZiLiao_Load_QiYeXinXi(int KeHuID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_GeRenZiLiao/FRM_GeRenZiLiao_Load_QiYeXinXi", ReplyAction="http://tempuri.org/FRM_GeRenZiLiao/FRM_GeRenZiLiao_Load_QiYeXinXiResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_GeRenZiLiao_Load_QiYeXinXiAsync(int KeHuID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_GeRenZiLiaoChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_GeRenZiLiao.FRM_GeRenZiLiao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_GeRenZiLiaoClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_GeRenZiLiao.FRM_GeRenZiLiao>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_GeRenZiLiao.FRM_GeRenZiLiao {
        
        public FRM_GeRenZiLiaoClient() {
        }
        
        public FRM_GeRenZiLiaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_GeRenZiLiaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_GeRenZiLiaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_GeRenZiLiaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_GeRenZiLiao_Load_GeRenXinXi(int KeHuID) {
            return base.Channel.FRM_GeRenZiLiao_Load_GeRenXinXi(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_GeRenZiLiao_Load_GeRenXinXiAsync(int KeHuID) {
            return base.Channel.FRM_GeRenZiLiao_Load_GeRenXinXiAsync(KeHuID);
        }
        
        public System.Data.DataSet FRM_GeRenZiLiao_Load_QiYeXinXi(int KeHuID) {
            return base.Channel.FRM_GeRenZiLiao_Load_QiYeXinXi(KeHuID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_GeRenZiLiao_Load_QiYeXinXiAsync(int KeHuID) {
            return base.Channel.FRM_GeRenZiLiao_Load_QiYeXinXiAsync(KeHuID);
        }
    }
}
