//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JingMaiFangShi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_JingMaiFangShi.FRM_JingMaiFangShi")]
    public interface FRM_JingMaiFangShi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JingMaiFangShi/FRM_JingMaiFangShi_Load", ReplyAction="http://tempuri.org/FRM_JingMaiFangShi/FRM_JingMaiFangShi_LoadResponse")]
        System.Data.DataSet FRM_JingMaiFangShi_Load(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_JingMaiFangShi/FRM_JingMaiFangShi_Load", ReplyAction="http://tempuri.org/FRM_JingMaiFangShi/FRM_JingMaiFangShi_LoadResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_JingMaiFangShi_LoadAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_JingMaiFangShiChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JingMaiFangShi.FRM_JingMaiFangShi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_JingMaiFangShiClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JingMaiFangShi.FRM_JingMaiFangShi>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_JingMaiFangShi.FRM_JingMaiFangShi {
        
        public FRM_JingMaiFangShiClient() {
        }
        
        public FRM_JingMaiFangShiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_JingMaiFangShiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JingMaiFangShiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_JingMaiFangShiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_JingMaiFangShi_Load(int GuaPaiID) {
            return base.Channel.FRM_JingMaiFangShi_Load(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_JingMaiFangShi_LoadAsync(int GuaPaiID) {
            return base.Channel.FRM_JingMaiFangShi_LoadAsync(GuaPaiID);
        }
    }
}
