//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ChuRangGongGao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_ChuRangGongGao.FRM_ChuRangGongGao")]
    public interface FRM_ChuRangGongGao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ChuRangGongGao/FRM_ChuRangGongGao_Load", ReplyAction="http://tempuri.org/FRM_ChuRangGongGao/FRM_ChuRangGongGao_LoadResponse")]
        System.Data.DataSet FRM_ChuRangGongGao_Load(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_ChuRangGongGao/FRM_ChuRangGongGao_Load", ReplyAction="http://tempuri.org/FRM_ChuRangGongGao/FRM_ChuRangGongGao_LoadResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_ChuRangGongGao_LoadAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_ChuRangGongGaoChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ChuRangGongGao.FRM_ChuRangGongGao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_ChuRangGongGaoClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ChuRangGongGao.FRM_ChuRangGongGao>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_ChuRangGongGao.FRM_ChuRangGongGao {
        
        public FRM_ChuRangGongGaoClient() {
        }
        
        public FRM_ChuRangGongGaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_ChuRangGongGaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_ChuRangGongGaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_ChuRangGongGaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_ChuRangGongGao_Load(int GuaPaiID) {
            return base.Channel.FRM_ChuRangGongGao_Load(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_ChuRangGongGao_LoadAsync(int GuaPaiID) {
            return base.Channel.FRM_ChuRangGongGao_LoadAsync(GuaPaiID);
        }
    }
}
