//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_GuaPaiChengJiao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPaiMaiXiTong.FRM_GuaPaiChengJiao.FRM_GuaPaiChengJiao")]
    public interface FRM_GuaPaiChengJiao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_GuaPaiChengJiao/FRM_DiKuaiXiangQing_Load", ReplyAction="http://tempuri.org/FRM_GuaPaiChengJiao/FRM_DiKuaiXiangQing_LoadResponse")]
        System.Data.DataSet FRM_DiKuaiXiangQing_Load(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_GuaPaiChengJiao/FRM_DiKuaiXiangQing_Load", ReplyAction="http://tempuri.org/FRM_GuaPaiChengJiao/FRM_DiKuaiXiangQing_LoadResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_DiKuaiXiangQing_LoadAsync(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_GuaPaiChengJiao/FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZha" +
            "iYao", ReplyAction="http://tempuri.org/FRM_GuaPaiChengJiao/FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZha" +
            "iYaoResponse")]
        System.Data.DataSet FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYao(int GuaPaiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FRM_GuaPaiChengJiao/FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZha" +
            "iYao", ReplyAction="http://tempuri.org/FRM_GuaPaiChengJiao/FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZha" +
            "iYaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYaoAsync(int GuaPaiID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRM_GuaPaiChengJiaoChannel : 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_GuaPaiChengJiao.FRM_GuaPaiChengJiao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRM_GuaPaiChengJiaoClient : System.ServiceModel.ClientBase<宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_GuaPaiChengJiao.FRM_GuaPaiChengJiao>, 宁夏土地和矿权拍卖系统_Client.BLLPaiMaiXiTong.FRM_GuaPaiChengJiao.FRM_GuaPaiChengJiao {
        
        public FRM_GuaPaiChengJiaoClient() {
        }
        
        public FRM_GuaPaiChengJiaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRM_GuaPaiChengJiaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_GuaPaiChengJiaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRM_GuaPaiChengJiaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FRM_DiKuaiXiangQing_Load(int GuaPaiID) {
            return base.Channel.FRM_DiKuaiXiangQing_Load(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_DiKuaiXiangQing_LoadAsync(int GuaPaiID) {
            return base.Channel.FRM_DiKuaiXiangQing_LoadAsync(GuaPaiID);
        }
        
        public System.Data.DataSet FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYao(int GuaPaiID) {
            return base.Channel.FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYao(GuaPaiID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYaoAsync(int GuaPaiID) {
            return base.Channel.FRM_ZhuFangBaoZhangXingBiLi_Load_ZiYuanZhaiYaoAsync(GuaPaiID);
        }
    }
}
